[package]
name = "vrc-tail"
version = "1.4.3"
edition = "2024"
description = "tail -f for VRChat logs"
license = "Zlib"

[dependencies]
chrono = "0.4"
clap = { version = "4.6", features = ["derive"] }
crossterm = "0.29"
notify = "8.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
