name: Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use stable Rust
        run: |
          rustup default stable
          rustup component add clippy rustfmt
      - name: Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --locked --target x86_64-pc-windows-msvc -- -D warnings
      - name: Test
        run: cargo test --locked --target x86_64-pc-windows-msvc
      - name: Build
        run: |
          cargo build --release --locked --target x86_64-pc-windows-msvc
          Copy-Item target/x86_64-pc-windows-msvc/release/vrc-tail.exe vrc-tail.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            vrc-tail.exe
      - name: make manifest
        run: pwsh -NoProfile -File scripts/makeManifest.ps1
      - name: Submit package to Windows Package Manager Community Repository
        run: |
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe submit --token "${{ secrets.WINGET_PAT }}" manifest/winget/generated
